AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'test/rails_app/**/*.rb'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120


Style/SignalException:
  Exclude:
    - 'lib/devise/passkeys/strategy.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Metrics/ModuleLength:
  Max: 300

Layout/LineLength:
  Max: 180

Lint/UselessAssignment:
  Exclude:
    - 'test/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'test/**/*.rb'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*.rb'

Naming/VariableNumber:
  Exclude:
    - 'test/**/*.rb'

Metrics/AbcSize:
  Exclude:
    - 'test/**/*.rb'